### ISSUE TITLE
category_index

### ISSUE THREAD

**Issue by FerasMorsi** [sglvladi/TensorFlowObjectDetectionTutorial#14]
Greetings, 
 i need some help in the roblem below can you please help me.

![image](https://user-images.githubusercontent.com/20375324/59975787-aff97280-95c4-11e9-8352-b2dbfff4315c.png)

**Comment by sglvladi** [comment]
@FerasMorsi 

Apologies for the late response. 

`PATH_TO_LABELS` must point to the location of the `*.pbtxt` file that contains the labels for all objects to be detected. In your case, it seems that `PATH_TO_LABELS = 'data\mscoco_label_map.pbtxt'`, which is relative to the directory where you have launched the Python interpreter and Python returns an error because it cannot locate the file.

For your code to work, you must place the file `mscoco_label_map.pbtxt` inside a `data` folder in the same directory where you called `python`.

Hope this helps.
