### ISSUE TITLE
Applying Custom Object Detector

### ISSUE THREAD

**Issue by saskra** [sglvladi/TensorFlowObjectDetectionTutorial#18]
Thanks a lot for this tutorial on training one's own object detector. But could you also give a hint about what to do after training, how to apply the model on test images?

PS: Different question, maybe not worth an own topic - where would I add early stopping to the pipeline?

**Comment by sglvladi** [comment]
@saskra Thanks for pointing that out. I will have a look at this once I get a chance.

In the meantime, you can customize the script provided under the [Detect Objects Using Your Webcam](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/camera.html#detect-objects-using-your-webcam) section to do detection based on your own model. All that you need to do is to replace `PATH_TO_CKPT` and `PATH_TO_LABELS` variables such that they point to the paths to your exported model and label files respectively, and then instead of reading frames from your camera, just read the images. Another example of how you can do the above can be found in the [`object_detection_tutorial.ipynb`](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb) notebook, which is used in the tutorial [here](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html#test-tf-models).

In terms of adding an early stop in the pipeline, I am not quite sure how this can be achieved. What I normally do is let the training run until a given checkpoint is achieved and then simply stop the training by using `Ctrl+C`. Then simply follow the [Exporting a Trained Inference Graph](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#exporting-a-trained-inference-graph) instructions to export your graph at the given checkpoint. To continue the training, you just rerun the command given under [Training the Model](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#training-the-model), and the training will start off from the last checkpoint automatically.
