### ISSUE TITLE
The images need to be squares.

### ISSUE THREAD

**Issue by turowicz** [sglvladi/TensorFlowObjectDetectionTutorial#23]
Hey I think you are leaving out one very important detail: for SSD the images need to be in square shape meaning width should equal height.

You are currently using fixed width reshaper which will skew the proportions of objects if the images aren't squares.

**Comment by sglvladi** [comment]
This is a good point, I'll see if I can fit this somewhere in future releases as a note. However, please note that the purpose of this tutorial is to get people quickly set-up and running with Tensorflow, rather than an advanced or one-for-all tutorial.

Thanks for your input.

**Comment by turowicz** [comment]
@sglvladi I understand the sentiment but your tutorial is very good actually and there are very few valuable resources on the subject such as yours.

**Comment by sglvladi** [comment]
@turowicz I recognise it's been a while since this issue was opened/closed, but just wanted to add a small note on SSD. Reading [this StackOverflow thread](https://stackoverflow.com/a/48151450) it seems like SSD requires the same image shape, rather than square images, and there is a mathematical explanation to this in the linked answer. 

In other words, all training images should have the same aspect ratio. Given that this is ensured, the width and height parameters of the ```fixed_shape_resizer``` in your ```*.config``` file can be adjusted accordingly.

For example, in one of my projects I have some images that are 704x576 pixels and some  1408x1152, i.e. that have double resolution. As I wanted to speed up the training, I configured the ```fixed_shape_resizer``` as follows:

```
model {
  ssd {
    ...
    image_resizer {
      fixed_shape_resizer {
        height: 352
        width: 288
      }
    }
...
  }
}
...
```

Hope this helps/makes sense.
