### ISSUE TITLE
webcam tutorial

### ISSUE THREAD

**Issue by snoopypi** [sglvladi/TensorFlowObjectDetectionTutorial#27]
hi there
first of all: thank you for your great tutorial.

now: the webcam detection works quite fine. now my question: i have a sterocamera system.. is it possible to use your code with two cameras?

second question: i would like to get the center of my bounding box. i am not sure how to change the code so that i always get the coordinates of the center back.

can you help me?

thanks so much.

**Comment by sglvladi** [comment]
I recognise that it's been a while since the issue was opened, but here are my comments.

I don't see why you shouldn't be able to run with two cameras. The script in the tutorial will most probably not work out of the box, but assuming you can get the corresponding frames from each camera, you shouldn't have an issue.

In terms of getting the center of the box, the bounding boxes that Tensorflow resurns are in the form ``(y_min, x_min, y_max, x_max)``. Therefore, to get the xy coordinates of the center of the box you can do the following:

``` python
def get_center(box):
    (y_min, x_min, y_max, x_max) = box
    x_center = x_min + (x_max-x_min)/2
    y_center = y_min + (y_max-y_min)/2
```

Hope this helps.
