### ISSUE TITLE
real-time detection

### ISSUE THREAD

**Issue by gpqls** [sglvladi/TensorFlowObjectDetectionTutorial#31]
I want to use webcam to detect objects as a model trained with my data.  What part of the code should be modified?

**Comment by sglvladi** [comment]
All that is need is `PATH_TO_CKPT` and `PATH_TO_LABELS` to be set to the respective paths to your generated `.ckpt` file and the `.pbtxt` containing the labels. You can also uncomment the block under the comment `#Download Model` to skip downloading another model, since you have your own, and you should be good to go.
